const data = {
  seed: '#0ea5e9',
  name: 'material-theme',
  description: 'TYPE: CUSTOM',
  baseline: false,
  extendedColors: [],
  coreColors: {
    primary: '#0ea5e9',
    secondary: '#ffffff',
    tertiary: '#6366f1',
    neutral: '#F6F8FA',
    neutralVariant: '#737373',
  },
  schemes: {
    light: {
      primary: '#006591',
      onPrimary: '#ffffff',
      primaryContainer: '#c9e6ff',
      onPrimaryContainer: '#001e2f',
      primaryFixed: '#c9e6ff',
      onPrimaryFixed: '#001e2f',
      primaryFixedDim: '#89ceff',
      onPrimaryFixedVariant: '#004c6e',
      secondary: '#006874',
      onSecondary: '#ffffff',
      secondaryContainer: '#97f0ff',
      onSecondaryContainer: '#001f24',
      secondaryFixed: '#97f0ff',
      onSecondaryFixed: '#001f24',
      secondaryFixedDim: '#4fd8eb',
      onSecondaryFixedVariant: '#004f58',
      tertiary: '#494bd6',
      onTertiary: '#ffffff',
      tertiaryContainer: '#e1e0ff',
      onTertiaryContainer: '#07006c',
      tertiaryFixed: '#e1e0ff',
      onTertiaryFixed: '#07006c',
      tertiaryFixedDim: '#c0c1ff',
      onTertiaryFixedVariant: '#2f2ebe',
      error: '#ba1a1a',
      errorContainer: '#ffdad6',
      onError: '#ffffff',
      onErrorContainer: '#410002',
      background: '#fbfcfe',
      onBackground: '#191c1d',
      outline: '#6f797a',
      inverseOnSurface: '#eff1f2',
      inverseSurface: '#2e3132',
      inversePrimary: '#89ceff',
      shadow: '#000000',
      surfaceTint: '#006591',
      outlineVariant: '#bfc8ca',
      scrim: '#000000',
      surface: '#f8f9fb',
      onSurface: '#191c1d',
      surfaceVariant: '#dbe4e6',
      onSurfaceVariant: '#3f484a',
      surfaceContainerHighest: '#e1e3e4',
      surfaceContainerHigh: '#e7e8ea',
      surfaceContainer: '#eceef0',
      surfaceContainerLow: '#f2f4f5',
      surfaceContainerLowest: '#ffffff',
      surfaceDim: '#d8dadc',
      surfaceBright: '#f8f9fb',
    },
    dark: {
      primary: '#89ceff',
      onPrimary: '#00344d',
      primaryContainer: '#004c6e',
      onPrimaryContainer: '#c9e6ff',
      primaryFixed: '#c9e6ff',
      onPrimaryFixed: '#001e2f',
      primaryFixedDim: '#89ceff',
      onPrimaryFixedVariant: '#004c6e',
      secondary: '#4fd8eb',
      onSecondary: '#00363d',
      secondaryContainer: '#004f58',
      onSecondaryContainer: '#97f0ff',
      secondaryFixed: '#97f0ff',
      onSecondaryFixed: '#001f24',
      secondaryFixedDim: '#4fd8eb',
      onSecondaryFixedVariant: '#004f58',
      tertiary: '#c0c1ff',
      onTertiary: '#1000a9',
      tertiaryContainer: '#2f2ebe',
      onTertiaryContainer: '#e1e0ff',
      tertiaryFixed: '#e1e0ff',
      onTertiaryFixed: '#07006c',
      tertiaryFixedDim: '#c0c1ff',
      onTertiaryFixedVariant: '#2f2ebe',
      error: '#ffb4ab',
      errorContainer: '#93000a',
      onError: '#690005',
      onErrorContainer: '#ffdad6',
      background: '#191c1d',
      onBackground: '#e1e3e4',
      outline: '#899294',
      inverseOnSurface: '#191c1d',
      inverseSurface: '#e1e3e4',
      inversePrimary: '#006591',
      shadow: '#000000',
      surfaceTint: '#89ceff',
      outlineVariant: '#3f484a',
      scrim: '#000000',
      surface: '#111415',
      onSurface: '#c5c7c8',
      surfaceVariant: '#3f484a',
      onSurfaceVariant: '#bfc8ca',
      surfaceContainerHighest: '#323537',
      surfaceContainerHigh: '#272a2c',
      surfaceContainer: '#1d2022',
      surfaceContainerLow: '#191c1d',
      surfaceContainerLowest: '#0c0f10',
      surfaceDim: '#111415',
      surfaceBright: '#373a3b',
    },
    androidLight: {
      colorAccentPrimary: '#c9e6ff',
      colorAccentPrimaryVariant: '#006591',
      colorAccentSecondary: '#97f0ff',
      colorAccentSecondaryVariant: '#006874',
      colorAccentTertiary: '#e1e0ff',
      colorAccentTertiaryVariant: '#494bd6',
      textColorPrimary: '#191c1d',
      textColorSecondary: '#3f484a',
      textColorTertiary: '#6f797a',
      textColorPrimaryInverse: '#eff1f2',
      textColorSecondaryInverse: '#c5c7c8',
      textColorTertiaryInverse: '#8f9193',
      colorBackground: '#eff1f2',
      colorBackgroundFloating: '#f8f9fb',
      colorSurface: '#f8f9fb',
      colorSurfaceVariant: '#e1e3e4',
      colorSurfaceHighlight: '#ffffff',
      surfaceHeader: '#e1e3e4',
      underSurface: '#000000',
      offState: '#2e3132',
      accentSurface: '#e9f2f4',
      textPrimaryOnAccent: '#191c1d',
      textSecondaryOnAccent: '#3f484a',
      volumeBackground: '#393c3d',
      scrim: '#c5c7c8',
    },
    androidDark: {
      colorAccentPrimary: '#c9e6ff',
      colorAccentPrimaryVariant: '#34b5fa',
      colorAccentSecondary: '#97f0ff',
      colorAccentSecondaryVariant: '#22bccf',
      colorAccentTertiary: '#e1e0ff',
      colorAccentTertiaryVariant: '#a0a3ff',
      textColorPrimary: '#eff1f2',
      textColorSecondary: '#bfc8ca',
      textColorTertiary: '#899294',
      textColorPrimaryInverse: '#191c1d',
      textColorSecondaryInverse: '#444749',
      textColorTertiaryInverse: '#757779',
      colorBackground: '#191c1d',
      colorBackgroundFloating: '#191c1d',
      colorSurface: '#2e3132',
      colorSurfaceVariant: '#444749',
      colorSurfaceHighlight: '#505354',
      surfaceHeader: '#444749',
      underSurface: '#000000',
      offState: '#2e3132',
      accentSurface: '#e9f2f4',
      textPrimaryOnAccent: '#191c1d',
      textSecondaryOnAccent: '#3f484a',
      volumeBackground: '#393c3d',
      scrim: '#c5c7c8',
    },
  },
  palettes: {
    primary: [
      '#000000',
      null,
      null,
      null,
      '#00101b',
      '#00131f',
      '#001523',
      null,
      null,
      null,
      '#001e2f',
      null,
      '#002235',
      null,
      null,
      null,
      null,
      '#002d44',
      null,
      null,
      '#00344d',
      null,
      '#003954',
      null,
      '#003d5a',
      '#00405d',
      null,
      null,
      null,
      null,
      '#004c6e',
      null,
      null,
      null,
      null,
      '#00587f',
      null,
      null,
      null,
      null,
      '#006591',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#007fb5',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#009ada',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#34b5fa',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#89ceff',
      null,
      null,
      null,
      null,
      null,
      null,
      '#b7dfff',
      null,
      null,
      '#c9e6ff',
      null,
      '#d4ebff',
      null,
      '#e0f0ff',
      '#e5f2ff',
      '#ebf5ff',
      null,
      '#f6faff',
      '#fcfcff',
      '#ffffff',
    ],
    secondary: [
      '#000000',
      null,
      null,
      null,
      '#001114',
      '#001417',
      '#00161a',
      null,
      null,
      null,
      '#001f24',
      null,
      '#002429',
      null,
      null,
      null,
      null,
      '#002f35',
      null,
      null,
      '#00363d',
      null,
      '#003b42',
      null,
      '#004047',
      '#00424a',
      null,
      null,
      null,
      null,
      '#004f58',
      null,
      null,
      null,
      null,
      '#005b66',
      null,
      null,
      null,
      null,
      '#006874',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#008391',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#00a0b0',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#22bccf',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#4fd8eb',
      null,
      null,
      null,
      null,
      null,
      null,
      '#68ecff',
      null,
      null,
      '#97f0ff',
      null,
      '#aff3ff',
      null,
      '#c5f6ff',
      '#d0f8ff',
      '#daf9ff',
      null,
      '#edfcff',
      '#f6feff',
      '#ffffff',
    ],
    tertiary: [
      '#000000',
      null,
      null,
      null,
      '#030045',
      '#03004d',
      '#040054',
      null,
      null,
      null,
      '#07006c',
      null,
      '#080078',
      null,
      null,
      null,
      null,
      '#0d0096',
      null,
      null,
      '#1000a9',
      null,
      '#170dae',
      null,
      '#1d17b2',
      '#201cb4',
      null,
      null,
      null,
      null,
      '#2f2ebe',
      null,
      null,
      null,
      null,
      '#3c3dca',
      null,
      null,
      null,
      null,
      '#494bd6',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#6366f1',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#8083ff',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#a0a3ff',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#c0c1ff',
      null,
      null,
      null,
      null,
      null,
      null,
      '#d7d6ff',
      null,
      null,
      '#e1e0ff',
      null,
      '#e8e6ff',
      null,
      '#eeecff',
      '#f2efff',
      '#f5f2ff',
      null,
      '#fcf8ff',
      '#fffbff',
      '#ffffff',
    ],
    neutral: [
      '#000000',
      null,
      null,
      null,
      '#0c0f10',
      '#0e1113',
      '#111415',
      null,
      null,
      null,
      '#191c1d',
      null,
      '#1d2022',
      null,
      null,
      null,
      null,
      '#272a2c',
      null,
      null,
      '#2e3132',
      null,
      '#323537',
      null,
      '#373a3b',
      '#393c3d',
      null,
      null,
      null,
      null,
      '#444749',
      null,
      null,
      null,
      null,
      '#505354',
      null,
      null,
      null,
      null,
      '#5c5f60',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#757779',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#8f9193',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#a9abad',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#c5c7c8',
      null,
      null,
      null,
      null,
      null,
      null,
      '#d8dadc',
      null,
      null,
      '#e1e3e4',
      null,
      '#e7e8ea',
      null,
      '#eceef0',
      '#eff1f2',
      '#f2f4f5',
      null,
      '#f8f9fb',
      '#fbfcfe',
      '#ffffff',
    ],
    neutralVariant: [
      '#000000',
      null,
      null,
      null,
      '#071011',
      '#091214',
      '#0c1516',
      null,
      null,
      null,
      '#141d1f',
      null,
      '#182123',
      null,
      null,
      null,
      null,
      '#222b2d',
      null,
      null,
      '#293234',
      null,
      '#2d3638',
      null,
      '#323b3c',
      '#343d3f',
      null,
      null,
      null,
      null,
      '#3f484a',
      null,
      null,
      null,
      null,
      '#4b5456',
      null,
      null,
      null,
      null,
      '#576062',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#6f797a',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#899294',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#a3adaf',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#bfc8ca',
      null,
      null,
      null,
      null,
      null,
      null,
      '#d2dcde',
      null,
      null,
      '#dbe4e6',
      null,
      '#e0eaec',
      null,
      '#e6f0f1',
      '#e9f2f4',
      '#ecf5f7',
      null,
      '#f2fbfd',
      '#f6feff',
      '#ffffff',
    ],
    error: [
      '#000000',
      null,
      null,
      null,
      '#280001',
      '#2d0001',
      '#310001',
      null,
      null,
      null,
      '#410002',
      null,
      '#490002',
      null,
      null,
      null,
      null,
      '#5c0004',
      null,
      null,
      '#690005',
      null,
      '#710005',
      null,
      '#790006',
      '#7e0007',
      null,
      null,
      null,
      null,
      '#93000a',
      null,
      null,
      null,
      null,
      '#a80710',
      null,
      null,
      null,
      null,
      '#ba1a1a',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#de3730',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#ff5449',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#ff897d',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      '#ffb4ab',
      null,
      null,
      null,
      null,
      null,
      null,
      '#ffcfc9',
      null,
      null,
      '#ffdad6',
      null,
      '#ffe2de',
      null,
      '#ffe9e6',
      '#ffedea',
      '#fff0ee',
      null,
      '#fff8f7',
      '#fffbff',
      '#ffffff',
    ],
  },
  styles: {
    display: {
      large: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 57,
        lineHeight: 64,
        letterSpacing: -0.25,
      },
      medium: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 45,
        lineHeight: 52,
        letterSpacing: 0,
      },
      small: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 36,
        lineHeight: 44,
        letterSpacing: 0,
      },
    },
    headline: {
      large: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 32,
        lineHeight: 40,
        letterSpacing: 0,
      },
      medium: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 28,
        lineHeight: 36,
        letterSpacing: 0,
      },
      small: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 24,
        lineHeight: 32,
        letterSpacing: 0,
      },
    },
    body: {
      large: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0.5,
      },
      medium: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.25,
      },
      small: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.4000000059604645,
      },
    },
    label: {
      large: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Medium',
        fontWeight: 500,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.10000000149011612,
      },
      medium: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Medium',
        fontWeight: 500,
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.5,
      },
      small: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Medium',
        fontWeight: 500,
        fontSize: 11,
        lineHeight: 16,
        letterSpacing: 0.5,
      },
    },
    title: {
      large: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Regular',
        fontWeight: 400,
        fontSize: 22,
        lineHeight: 28,
        letterSpacing: 0,
      },
      medium: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Medium',
        fontWeight: 500,
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0.15000000596046448,
      },
      small: {
        fontFamilyName: 'Roboto',
        fontFamilyStyle: 'Medium',
        fontWeight: 500,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.10000000149011612,
      },
    },
  },
  customColors: [],
}
